let Price = prompt("Name your price")
let Discount = ("0.1")
let Price2 = (420)
let Price3 = (300)
let Price4 =(1200)
let Price5 = (4200)

console.log(Price * Discount)
console.log(Price2 * Discount)
console.log(Price3 * Discount)
console.log(Price4 * Discount)
console.log(Price5 * Discount)